### ISSUE TITLE
Перевод набранного текста

### ISSUE THREAD

**Issue by becauseim** [fantomnotabene/Alfred-GTranslator-workflow#8]
Привет! Только установил, на первый взгляд, отлично работает! Хочется иметь возможность переводить набранный текст, а не только выводить его на экран с возможностью скопировать. То есть по заданному сочетанию клавиш заменять (как это реализовано [здесь](https://github.com/voldmar/alfred-typograf?files=1)) выделенный набранный текст на переведенный.

**Comment by fantomnotabene** [comment]
Приветствую. Нажатие `enter` на переведенном тексте копирует его в буфер обмена. После этого его можно просто вставить (`cmd+v`).

**Comment by fantomnotabene** [comment]
В любом случае, я, скорее всего, сегодня до вечера выкину фикс для соседнего ишью. И посмотрю что можно сделать c этим. 
Думаю, большой проблемы нет добавить что-то вроде `cmd+shift+c` для замены выделенного в поле ввода текста его переводом.

**Comment by fantomnotabene** [comment]
[Новый релиз v1.3](https://github.com/fantomnotabene/Alfred-GTranslator-workflow/releases/tag/1.3)

**Comment by becauseim** [comment]
> [Новый релиз v1.3](https://github.com/fantomnotabene/Alfred-GTranslator-workflow/releases/tag/1.3)

работает! спасибо!
