### ISSUE TITLE
Перевод абзаца текста

### ISSUE THREAD

**Issue by becauseim** [fantomnotabene/Alfred-GTranslator-workflow#9]
В одну строку результата запроса не умещается текст более одного короткого предложения. Приходится выносить результат в текстовый редактор.

Если текста в буфере свыше заданного объема, а интерфейс Alfred 4 не подразумевает увеличения количества строк в результате, то может, добавить вывод результата перевода в окно (элемент интерфейса ОС)?

**Comment by fantomnotabene** [comment]
Примерно для этого сделан cmd+enter, который открывает введенный текст в браузере на сайте переводчика. Там же можно посмотреть весь перевод, скопировать весь или часть и даже продолжать редактировать исходный и видеть изменения в переводе. Чем не решение?
